### ISSUE TITLE
How do I identify which components on the list are the ones on the pictures/blueprints?

### ISSUE THREAD

**Issue by Ejdems666** [cphdat2sem2017-Cos/COS-shared-projectinfo#2]
Hi,

am I the only one who's wondering how do the components form the list look on the picture?
And I don't mean the brackets and screws.
This for example:
![image](https://cloud.githubusercontent.com/assets/16317128/24625287/d310a602-18ae-11e7-84c9-39dacf2d7d02.png)

Not sure which are the vertical pillars, which are the roof support, etc.

If anybody figured this out, it'd be nice to share some insights.

**Comment by kaspercphbusiness** [comment]
I found this picture on Fog's carport page (yes it is small). 
![productpage](https://cloud.githubusercontent.com/assets/17823636/24643907/e19736ca-1910-11e7-90a7-bd2451130709.png)

Link: https://www.johannesfog.dk/byggecenter/produkter/2CARPORT_CP01DUR/?code=2476623

I believe (from the Danish wordings) that it is the wood that sits along the roof. The dimensions are odd as one cannot get wood longer than 6 meter normally, so one has to put it two (or more) pieces together.  But the lengths do not seem to add up to 6.0 by 7,8 meter. (We need 27.6 meter, but get 36)

Should I ask about it?

**Comment by Ejdems666** [comment]
Yes, If you could ask to mark items from the list on the blueprint and also associate brackets and screw with wood, it would help a lot.

Everytime we try to produce something we find ourselves without knowledge about this and we can't really move anywhere. 

Btw. Is there any way to contact Fog other than through you? In order to make something meaningful I still have to ask a lot of questions.

**Comment by Ejdems666** [comment]
So is there any update?
